// <auto-generated />
using System;
using AracKirala.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace AracKirala.Migrations
{
    [DbContext(typeof(AracKiralaDBContext))]
    [Migration("20230625102206_arasirket")]
    partial class arasirket
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.19")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("AracKirala.Data.Entities.Arac", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<decimal>("GunlukUcret")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Km")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Marka")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Modeli")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Plaka")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("SaatlikUcret")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int?>("sirketId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("sirketId");

                    b.ToTable("Araclar");
                });

            modelBuilder.Entity("AracKirala.Data.Entities.AracPolice", b =>
                {
                    b.Property<int>("PoliceId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PoliceId"), 1L, 1);

                    b.Property<int>("AracId")
                        .HasColumnType("int");

                    b.Property<DateTime>("PoliceBaslangicTarihi")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("PoliceBitisTarihi")
                        .HasColumnType("datetime2");

                    b.Property<string>("PoliceNumara")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("PoliceId");

                    b.HasIndex("AracId")
                        .IsUnique();

                    b.ToTable("AracPoliceler");
                });

            modelBuilder.Entity("AracKirala.Data.Entities.Sirket", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Adres")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Isim")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Sirket");
                });

            modelBuilder.Entity("AracKirala.Data.Entities.Arac", b =>
                {
                    b.HasOne("AracKirala.Data.Entities.Sirket", "AracSirket")
                        .WithMany("Araclar")
                        .HasForeignKey("sirketId");

                    b.Navigation("AracSirket");
                });

            modelBuilder.Entity("AracKirala.Data.Entities.AracPolice", b =>
                {
                    b.HasOne("AracKirala.Data.Entities.Arac", "Arac")
                        .WithOne("Police")
                        .HasForeignKey("AracKirala.Data.Entities.AracPolice", "AracId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Arac");
                });

            modelBuilder.Entity("AracKirala.Data.Entities.Arac", b =>
                {
                    b.Navigation("Police")
                        .IsRequired();
                });

            modelBuilder.Entity("AracKirala.Data.Entities.Sirket", b =>
                {
                    b.Navigation("Araclar");
                });
#pragma warning restore 612, 618
        }
    }
}
